# frozen_string_literal: true

require "json"
require "minitest/autorun"
require "tempfile"

require_relative "../tools/r10_manual_classification"

class TestR10ManualClassification < Minitest::Test
  SCAN = File.expand_path("../data/r10_corpus_scan.json", __dir__)
  LEDGER = File.expand_path("../data/r10_manual_classification.json", __dir__)

  def setup
    @scan = R10ManualClassification.load(SCAN)
    @ledger = R10ManualClassification.load(LEDGER)
  end

  def test_ledger_is_complete_and_valid
    assert_empty R10ManualClassification.validate(@ledger, @scan)
  end

  def test_every_scanner_finding_has_exactly_one_review
    scan_targets = R10ManualClassification.scan_targets(@scan)
    @ledger.fetch("targets").each do |target|
      expected = scan_targets.fetch(target.fetch("name")).dig("scanner", "findings") || []
      actual = target.fetch("candidate_reviews")
      assert_equal expected.size, actual.size, target.fetch("name")
      assert_equal actual.size, actual.map { |review| review.fetch("finding_key") }.uniq.size,
                   target.fetch("name")
    end
  end

  def test_verification_is_not_inferred_from_source_classification
    @ledger.fetch("targets").each do |target|
      verification = target.fetch("verification")
      assert_includes %w[not_run recorded_not_rerun pass fail inconclusive], verification.fetch("control")
      assert_includes %w[not_run recorded_not_rerun pass fail inconclusive], verification.fetch("rubycc")
      assert_includes %w[not_run recorded_not_rerun pass fail inconclusive], verification.fetch("extension_load")
      assert_includes %w[not_run recorded_not_rerun pass fail inconclusive], verification.fetch("upstream_suite")
    end
  end

  def test_zero_finding_assessments_keep_scoped_evidence_separate
    zero_targets = @ledger.fetch("targets").select { |target| target.fetch("candidate_reviews").empty? }
    assert_equal 29, zero_targets.size
    assert_equal 20, zero_targets.count { |target| target.dig("zero_finding_review", "classification") == "scoped_no_candidate" }
    assert_equal 1, zero_targets.count { |target| target.dig("zero_finding_review", "classification") == "non_target_variadic_wrapper" }
    assert_equal 8, zero_targets.count { |target| target.dig("zero_finding_review", "classification") == "needs_more_evidence" }
    assert zero_targets.all? { |target| target.fetch("manual") == "no_candidate" }
    assert_equal "preprocessor_inactive", @ledger.fetch("targets").find { |target| target.fetch("name") == "nkf" }.fetch("candidate_reviews").first.fetch("selected_in_build")
  end

  def test_declared_path_and_generated_provenance_are_not_invented_as_compile_proof
    http = @ledger.fetch("targets").find { |target| target.fetch("name") == "http_parser.rb" }
    assert_equal ["ext/ruby_http_parser/ruby_http_parser.c"], http.dig("selected_build_path", "translation_units")
    assert_includes http.dig("selected_build_path", "non_selected_sources"), "ext/ruby_http_parser/ryah_http_parser.c (generated by extconf.rb)"
    assert_equal "generated_not_reproduced", http.dig("selected_build_path", "generated_source", "status")
    assert_nil http.dig("provenance", "source_tarball_sha256")
    refute_empty http.dig("provenance", "source_tree_sha256")
    assert_match(/not yet captured/, http.dig("selected_build_path", "source_selection_status"))
  end

  def test_c_assessment_requires_an_explicit_follow_up
    candidate = Marshal.load(Marshal.dump(@ledger))
    target = candidate.fetch("targets").find { |entry| entry.fetch("name") == "prism" }
    target.fetch("zero_finding_review").fetch("follow_up").delete("next_action")
    refute_empty R10ManualClassification.validate(candidate, @scan)
  end

  def test_recorded_verification_artifacts_are_portable_and_preserve_inconclusive_runs
    %w[data/r10_verification_m4a.json data/r10_verification_m4b.json data/r10_verification_m4c.json data/r10_verification_m4d.json data/r10_verification_rbs.json].each do |relative|
      path = File.expand_path("../#{relative}", __dir__)
      assert File.file?(path), relative
      json = JSON.parse(File.read(path))
      serialized = JSON.generate(json)
      refute_match(%r{"(?:/tmp|/home)/}, serialized, relative)
    end

    nkf = @ledger.fetch("targets").find { |target| target.fetch("name") == "nkf" }
    assert_equal "inconclusive", nkf.dig("verification", "upstream_suite")
    rbs = @ledger.fetch("targets").find { |target| target.fetch("name") == "rbs" }
    assert_equal "inconclusive", rbs.dig("verification", "upstream_suite")
    assert_equal "pass", rbs.dig("verification", "extension_load")
    sqlite3 = @ledger.fetch("targets").find { |target| target.fetch("name") == "sqlite3" }
    assert_equal "inconclusive", sqlite3.dig("verification", "control")
    assert_equal "not_run", sqlite3.dig("verification", "upstream_suite")
  end

  def test_verification_state_is_derived_from_the_artifact
    candidate = Marshal.load(Marshal.dump(@ledger))
    target = candidate.fetch("targets").find { |entry| entry.fetch("name") == "bootsnap" }
    target.fetch("verification")["upstream_suite"] = "pass"
    errors = R10ManualClassification.validate(candidate, @scan)
    assert errors.any? { |error| error.include?("bootsnap: upstream suite state inconclusive disagrees") }
  end

  def test_a_pass_artifact_requires_a_non_empty_suite_summary
    result = {
      "status" => "pass",
      "summary" => nil
    }
    refute R10ManualClassification.summary_valid?(result)
    assert R10ManualClassification.summary_valid?(
      "status" => "pass",
      "summary" => {
        "tests" => 1,
        "failures" => 0,
        "errors" => 0,
        "other" => {}
      }
    )
  end

  def test_measured_state_requires_the_referenced_artifact
    candidate = Marshal.load(Marshal.dump(@ledger))
    target = candidate.fetch("targets").find { |entry| entry.fetch("name") == "bootsnap" }
    target.fetch("verification_evidence").fetch("upstream_suite")["artifact"] = "data/does-not-exist.json"
    errors = R10ManualClassification.validate(candidate, @scan)
    assert errors.any? { |error| error.include?("bootsnap: upstream_suite artifact is required") }
  end

  def test_explicit_build_and_summary_state_cannot_override_evidence
    source_path = File.expand_path("../data/r10_verification_m4a.json", __dir__)
    artifact = JSON.parse(File.read(source_path))
    artifact.fetch("control").find { |result| result.fetch("name") == "json" }.tap do |result|
      result["evidence"] = []
      result["build_state"] = "pass"
    end

    Tempfile.create(["r10-artifact-", ".json"], File.expand_path("../data", __dir__)) do |file|
      file.write(JSON.pretty_generate(artifact))
      file.flush
      relative = "data/#{File.basename(file.path)}"
      candidate = Marshal.load(Marshal.dump(@ledger))
      target = candidate.fetch("targets").find { |entry| entry.fetch("name") == "json" }
      target.fetch("verification_evidence").each_value { |evidence| evidence["artifact"] = relative }
      errors = R10ManualClassification.validate(candidate, @scan)
      assert errors.any? { |error| error.include?("json: control build_state is missing or disagrees") }
    end
  end

  def test_summary_line_must_be_reproducible_by_verify_tool
    artifact = JSON.parse(File.read(File.expand_path("../data/r10_verification_m4a.json", __dir__)))
    result = artifact.fetch("control").find { |entry| entry.fetch("name") == "json" }
    assert R10ManualClassification.summary_matches_verify_tool?(result)
    malformed = Marshal.load(Marshal.dump(result))
    malformed.fetch("summary")["line"].sub!("603 tests", "603, tests")
    refute R10ManualClassification.summary_matches_verify_tool?(malformed)
  end
  # The per-target reviewer is a single agent, and the same one that wrote the
  # scanner. The cross review is the independent layer, so it has to be a real
  # check rather than a stamp: each of these mutations must be rejected.
  def test_cross_review_must_be_independent_and_account_for_every_finding
    assert_empty R10ManualClassification.validate(@ledger, @scan)

    mutations = {
      "a reviewer who also classified targets" =>
        ->(l) { l["cross_review"]["reviewer"] = l["targets"].first["reviewer"] },
      "a target with findings left out of scope" =>
        ->(l) { l["cross_review"]["scope"]["targets"] -= ["oj"] },
      "a findings_covered count that does not match" =>
        ->(l) { l["cross_review"]["scope"]["findings_covered"] -= 1 },
      "no cross review at all" =>
        ->(l) { l.delete("cross_review") },
      "an unsupported verdict" =>
        ->(l) { l["cross_review"]["verdict"] = "looks fine" },
      "an issue with no impact recorded" =>
        ->(l) { l["cross_review"]["issues_raised"].first["impact"] = "" }
    }

    mutations.each do |description, mutate|
      ledger = Marshal.load(Marshal.dump(@ledger))
      mutate.call(ledger)
      errors = R10ManualClassification.validate(ledger, @scan).grep(/cross_review/)
      refute_empty errors, "the cross review accepted #{description}"
    end
  end

  def test_cross_review_scope_covers_every_target_that_carries_findings
    scoped = @ledger.fetch("cross_review").fetch("scope").fetch("targets")
    with_findings = @ledger.fetch("targets").reject { |t| Array(t["candidate_reviews"]).empty? }

    assert_equal with_findings.map { |t| t.fetch("name") }.sort, scoped.sort
    assert_equal with_findings.sum { |t| t.fetch("candidate_reviews").length },
                 @ledger.fetch("cross_review").fetch("scope").fetch("findings_covered")
  end

end
