#!/usr/bin/env ruby
# frozen_string_literal: true

require "rubycc"

if ARGV.include?("--version") || ARGV.include?("-v")
  puts "rubycc #{Rubycc::VERSION}"
  exit 0
end

warn "rubycc: C compilation is not yet implemented"
exit 1
